name: sgp_movil
description: "Sistema para la gestion de personal en movil."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  intl: ^0.19.0
  go_router: ^14.8.1
  google_fonts: ^4.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.4.9
  logging: ^1.2.0
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.6
  decimal: ^3.0.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.4
  sqflite_sqlcipher: ^2.1.0+2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.7
  flutter_local_notifications: ^19.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  change_app_package_name: ^1.5.0 
  flutter_launcher_icons: "^0.12.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ferbo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "0x3833CDFF"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/gifs/
    - assets/images/
    - assets/icons/
    - google_fonts/montserrat_alternates/
