export 'datasources/incapacidad_datasource.dart';
export 'datasources/incapacidad_detalle_datasource.dart';
export 'entities/incapacidad.dart';
export 'entities/incapacidad_detalle.dart';
export 'entities/incapacidad_guardar_detalle.dart';
export 'entities/empleado_incapacidad.dart';
export 'entities/tipo_incapacidad.dart';
export 'repositories/incapacidad_repository.dart';
export 'repositories/incapacidad_detalle_repository.dart';
